/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDialogLogin: typeof import('./src/components/TheDialogLogin.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    TheViewLabelProgress: typeof import('./src/components/TheViewLabelProgress.vue')['default']
    TheViewLabelResult: typeof import('./src/components/TheViewLabelResult.vue')['default']
    TheViewLabelSubject: typeof import('./src/components/TheViewLabelSubject.vue')['default']
    TheViewToolbar: typeof import('./src/components/TheViewToolbar.vue')['default']
    VDataEntry: typeof import('./src/components/VDataEntry.vue')['default']
    VDialog: typeof import('./src/components/VDialog.vue')['default']
    VMessage: typeof import('./src/components/VMessage.vue')['default']
    VMessages: typeof import('./src/components/VMessages.vue')['default']
  }
}
